import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import AppNavbar from "@/components/AppNavbar/AppNavbar";
import { NextIntlClientProvider, useMessages } from "next-intl";
import { blacker, jost } from "@/assets/fonts";

export const metadata: Metadata = {
  title: "André Rodrigo",
  description: "Generated by create next app"
};

export default function RootLayout({
  children,
  params: { locale }
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = useMessages();

  return (
    <html lang={locale} className={`${jost.variable} ${blacker.variable}`}>
      <body className="min-h-screen">
        <NextIntlClientProvider messages={messages}>
          <AppNavbar />
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
