import type { Metadata } from "next";

import "./globals.scss";
import AppNavbar from "@/components/AppNavbar/AppNavbar";
import { NextIntlClientProvider, useMessages } from "next-intl";
import { blacker, italiana, jost, moniqa } from "@/assets/fonts";
import Footer from "@/components/Footer/Footer";

export const metadata: Metadata = {
  title: "André Rodrigo",
  description: "Generated by create next app"
};

export default function RootLayout({
  children,
  params: { locale }
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = useMessages();

  return (
    <html
      lang={locale}
      className={`${jost.variable} ${blacker.variable} ${italiana.variable} ${moniqa.variable}`}
    >
      <body className="min-h-screen">
        <NextIntlClientProvider messages={messages}>
          <AppNavbar />
          {children}
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
